language: java
env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "BpZB7xQ/TQEM79gN6CPkZ5t/xlw+BWLn5TjAS7DzmNAy2UNka/apr6AbFcampUSJaxvPjl4zkqatlRjEjGvv3O/SIFZRP1x0GQsVoGvpC6xbTTgPohJ1wRkkQQrlGONOr+SpNNBT7kgZAZPKuZ7k4lBvngYwPzgpfxxgzkiIZzqxuY5dGaohIpzmdcHFSzw6XOowxeRLr+pN2ELzuA69bA7mp82euyL9JxUhrAAY0pTezMJF3NXLswPNZTtVMajDIm+7reL2JX0CyNaCsgKgv727x4mMOKkJN4tsCsNAw0BmYlaVGSVkWfPvLjvya7zq/kn6v9yglwSYBYuZteQ9p0oGvmEPOx1mQlevt46KSz0Wl+mE+gTUlwR10dcJOzTc3TBYbqUDkMawIsyWznMrojG4VPmdVHzi9MnHLU1RrRBAv7e348UTHLUb89nKWLh2ot6RVxocbEDZtJVGX1zPkpDWt3bSvxOnNdxb18u4cB1eNS+AM7tQaox48G7bMpFUPJWwXWuZbbVA8UH9bZu/d82V9lIm/IO2RALRm0zZFfC1+w40b58NzMJ8SIXaH8QDdIOAYYuuIJZGyiNz/oKT7ssOEfNy6IIM4HiaMNZ2zAhnEJoEwTXax4qAkm16mvxYGv16G0WZZGYPu0oZjPIHgjJUaTM4MbzC2uOZ2oOLhBg="

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

before_script:
  - version=$(grep -oP '(?<=^    <version>)[^<]*' pom.xml)

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - echo "Parsed the version $version from pom.xml" 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Prun-its

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: itsallcode/openfasttrace-maven
      version: $version
      description: OpenFastTrace Maven Plugin
    notification_email: christoph@users.sourceforge.net
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "itsallcode"
    token:
      secure: "VoF2eYvAzqf7TtcmqczI0uZFunkxOkfZL6VJGv0u/HQiZNe8Yq0G4nBurH7RZ25tlIG8OTTJenVNiB8R1F3Dja6eAV81vYC/jD67RfRE/saELlMIwWfKQosAtjIIPTep/Ri4IKOiiEIQvxNqYSIlDOTPeoRofx/cB16P5EkudwMqxKWY7VaJb49XoRvhlaaCO7m+yw0BTglFm/cs9aX/HJGKJzwcb5rY10wx4wiElk+CeZeNQbso8Y5cM2UBs0vYnPZnhKsAb5ODk++X43kvwvlDzZzDe/14cVIZz6g18GSc/qv3kyPvyi9eACXVd/lx6Gsj4gcBIxUtHiNsK42lgEbWF5CBbgVz8vZzhdHAOHtXkGsFLeYhv3VKh4/tdlJnVBZ3hCGTXh9DUbb7zoNk1/I1n2ynVshfPUOqQDdmREWVpqRv7eIZjAEF4lNy83E385IFraxFSZIuxaxQc/FGT4SWHyR77jJOdYU3qLa/Q36zRcJF3WEsBBON1/b/Zr9ZqG6ECojmCB9Y6JTqUtBPUMa/1rZm0zj25/GIUkD87nYyZb75riwIKfU94oUz7ZHeNHaKhPi3zAbT+yK2FTvEbssY1kAdmLW97XrFqgiEBFFndxlOzL6/AuQbSGu1hRxyry1ifrio2tF3sAcTWwoff1feO8A9dCOTOS267Dz2UtM="